# FilePath    : video-trim\config.yaml
# Author      : jiaopengzi
# Blog        : https://jiaopengzi.com
# Copyright   : Copyright (c) 2026 by jiaopengzi, All Rights Reserved.
# Description : 配置文件

# 上传文件存放目录
upload_dir: "./uploads"

# 输出文件存放目录
output_dir: "./outputs"

# 掐头:多少秒(默认 6)
head_trim_seconds: 6

# 去尾:多少秒(默认 0)
tail_seconds: 0

# 服务器监听端口
server_port: ":5678"

# 单个文件最大允许上传大小(单位: 字节), 默认2GB
max_upload_size: 2147483648

# ====================== 超时设置开始(单位: 秒) ======================
# 读取超时
read_timeout_seconds: 15

# 写入超时
write_timeout_seconds: 60

# 空闲连接超时
idle_timeout_seconds: 120
# ====================== 超时设置结束(单位: 秒) ======================
